version: '3.9'

services:
  mysqldb:
    image: mysql:8.0.28-oracle
    container_name: case-mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - 'local-network'
    ports:
      - '3306:3306'
    volumes:
      - case-mysql-data:/var/lib/mysql
      - ./mysql-db-dump.sql:/docker-entrypoint-initdb.d/mysql-db-dump.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-engineering-case-study
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/mysql-db?allowPublicKeyRetrieval=true
    networks:
      - 'local-network'

  test:
    image: maven:3.8.8-eclipse-temurin-17
    container_name: backend-engineering-case-study-test
    depends_on:
      - app
    working_dir: /app
    volumes:
      - .:/app
    command: [ "mvn", "test" ]
    networks:
      - 'local-network'

volumes:
  case-mysql-data:


networks:
  local-network:
    driver: bridge
